name: reina

services:
  nginx:
    container_name: nginx
    image: "nginx:alpine"
    ports:
      - "80:80"
      - "443:443"
      - "8080:80"
    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/reina
      - ./_docker/cert/Certificate.crt:/etc/ssl/certs/reina.online/Certificate.crt:ro
      - ./_docker/cert/PrivateKey.key:/etc/ssl/private/reina.online/PrivateKey.key:ro
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - php
    networks:
      - reina_network

  php:
    container_name: php
    build:
      context: .
      dockerfile: _docker/php/php.Dockerfile
    volumes:
      - ./_docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./_docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./_docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - .:/var/www/reina
    restart: unless-stopped
    networks:
      - reina_network
# docker exec -it php /bin/sh -c "chmod -R 755 /var/www/reina/public && chown -R www-data:www-data /var/www/reina/public"

  timescale:
    container_name: timescale
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5433:5433"
    environment:
      DB_HOST: ${DB_TIMESCALE_HOST}
      DB_PORT: ${DB_TIMESCALE_PORT}
      POSTGRES_DB: ${DB_TIMESCALE_DATABASE}
      POSTGRES_USER: ${DB_TIMESCALE_USERNAME}
      POSTGRES_PASSWORD: ${DB_TIMESCALE_PASSWORD}
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - reina_network
    command: ["postgres", "-p", "5433"]

  postgres:
      container_name: postgres
      image: postgres:bookworm
      ports:
          - "5432:5432"
      environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
          - postgres_data:/var/lib/postgresql/data
      restart: unless-stopped
      networks:
          - reina_network

  redis:
    container_name: redis
    image: redis:8-bookworm
    ports:
      - '6379:6379'
    environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./_docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    networks:
      - reina_network

  node:
    container_name: node
    image: node:lts-alpine
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/reina
      - ./_docker/cert/Certificate.crt:/etc/ssl/certs/reina.online/Certificate.crt:ro
      - ./_docker/cert/PrivateKey.key:/etc/ssl/private/reina.online/PrivateKey.key:ro
    working_dir: /var/www/reina
    tty: true
    networks:
      - reina_network

volumes:
  postgres_data:
  redis_data:
  timescale_data:

networks:
  reina_network:
    driver: bridge

#    docker-compose exec php composer update
#    docker-compose exec node npm update
#    docker-compose exec node npm run dev
